// commands.js
export const commands = [
    { name: 'REM', inputs: ['comment'], description: 'Adds a comment.' },
    { name: 'DEFAULTDELAY', inputs: ['delay'], description: 'Sets the default delay between commands in milliseconds.' },
    { name: 'DEFAULTCHARDELAY', inputs: ['delay'], description: 'Sets the default delay between keystrokes in milliseconds.' },
    { name: 'DELAY', inputs: ['milliseconds'], description: 'Pauses execution for a specified time.' },
    { name: 'STRING', inputs: ['text'], description: 'Types out a string.' },
    { name: 'STRINGLN', inputs: ['text'], description: 'Types out a string and presses Enter.' },
    { name: 'REPEAT', inputs: ['times'], description: 'Repeats the last command.' },
    { name: 'WINDOWS', inputs: [], description: 'Presses the Windows key.' },
    { name: 'GUI', inputs: [], description: 'Alias for WINDOWS key.' },
    { name: 'CONTROL', inputs: [], description: 'Presses the Control key.' },
    { name: 'CTRL', inputs: [], description: 'Alias for CONTROL key.' },
    { name: 'ALT', inputs: [], description: 'Presses the Alt key.' },
    { name: 'SHIFT', inputs: [], description: 'Presses the Shift key.' },
    { name: 'ENTER', inputs: [], description: 'Presses the Enter key.' },
    { name: 'MENU', inputs: [], description: 'Presses the Menu key.' },
    { name: 'APP', inputs: [], description: 'Alias for MENU key.' },
    { name: 'TAB', inputs: [], description: 'Presses the Tab key.' },
    { name: 'CAPSLOCK', inputs: [], description: 'Toggles Caps Lock.' },
    { name: 'PRINTSCREEN', inputs: [], description: 'Presses the Print Screen key.' },
    { name: 'SCROLLLOCK', inputs: [], description: 'Toggles Scroll Lock.' },
    { name: 'PAUSE', inputs: [], description: 'Presses the Pause key.' },
    { name: 'BREAK', inputs: [], description: 'Presses the Break key.' },
    { name: 'INSERT', inputs: [], description: 'Presses the Insert key.' },
    { name: 'HOME', inputs: [], description: 'Presses the Home key.' },
    { name: 'PAGEUP', inputs: [], description: 'Presses the Page Up key.' },
    { name: 'PAGEDOWN', inputs: [], description: 'Presses the Page Down key.' },
    { name: 'DELETE', inputs: [], description: 'Presses the Delete key.' },
    { name: 'END', inputs: [], description: 'Presses the End key.' },
    { name: 'ESC', inputs: [], description: 'Presses the Escape key.' },
    { name: 'UP', inputs: [], description: 'Presses the Up Arrow key.' },
    { name: 'DOWN', inputs: [], description: 'Presses the Down Arrow key.' },
    { name: 'LEFT', inputs: [], description: 'Presses the Left Arrow key.' },
    { name: 'RIGHT', inputs: [], description: 'Presses the Right Arrow key.' },
    { name: 'SPACE', inputs: [], description: 'Presses the Space key.' },
    { name: 'F1', inputs: [], description: 'Presses the F1 key.' },
    { name: 'F2', inputs: [], description: 'Presses the F2 key.' },
    { name: 'F3', inputs: [], description: 'Presses the F3 key.' },
    { name: 'F4', inputs: [], description: 'Presses the F4 key.' },
    { name: 'F5', inputs: [], description: 'Presses the F5 key.' },
    { name: 'F6', inputs: [], description: 'Presses the F6 key.' },
    { name: 'F7', inputs: [], description: 'Presses the F7 key.' },
    { name: 'F8', inputs: [], description: 'Presses the F8 key.' },
    { name: 'F9', inputs: [], description: 'Presses the F9 key.' },
    { name: 'F10', inputs: [], description: 'Presses the F10 key.' },
    { name: 'F11', inputs: [], description: 'Presses the F11 key.' },
    { name: 'F12', inputs: [], description: 'Presses the F12 key.' },
];